### PR TITLE
Update Team.md for the summer #7

### PR DESCRIPTION
**Pull request by yamgent**

### CODE REVIEW

**Comment by yamgent** [comment]
CanIHasReview is not supported on this repo.

**Comment by yamgent** [comment]
@Zhiyuan-Amos @limmlingg Might want to add your photos in too.

**Comment by damithc** [comment]
> @Zhiyuan-Amos @limmlingg Might want to add your photos in too.

Yes, may be pass the photos to @yamgent so that they can be added at the same time? Otherwise the page will show broken links. Alternatively remove the broken image link altogether.

**Comment by Zhiyuan-Amos** [comment]
Should we update the timeline for past members? For example, some of their contributions timeline look something like `[2016 May - ]`, however, they have already stopped contributing for quite some time.

**Comment by yamgent** [comment]
> Should we update the timeline for past members? For example, some of their contributions timeline look something like [2016 May - ], however, they have already stopped contributing for quite some time.

Ok, will update accordingly.

**Comment by yamgent** [comment]
@damithc Added the photos and updated the timeline.

**Pull request merged**
