### PR TITLE
Port over documentation template from AB-4

### PR DESCRIPTION
**Pull request by pyokagan**

### CODE REVIEW

**Comment by pyokagan** [comment]
@damithc No netlify :-P

I've setup staging at https://pyokagan.github.io/se-edu.github.io/

**Comment by damithc** [comment]
> @damithc No netlify :-P

dome

**Comment by pyokagan** [comment]
@damithc Doesn't seem to be triggering though.

Anyway, what do you think (from the staging website)? Approve?

**Comment by pyokagan** [comment]
@damithc wrt to https://github.com/se-edu/addressbook-level4/pull/762#issuecomment-353774298 , I guess the "branch to deploy" needs to be set to the `docs` branch.

**Comment by damithc** [comment]
> @damithc wrt to se-edu/addressbook-level4#762 (comment) , I guess the "branch to deploy" needs to be set to the docs branch.

sorry forgot about it. Like this?
image




> what do you think (from the staging website)? Approve?

Yes, looks good. 👍

**Comment by pyokagan** [comment]
@damithc The deploy preview works now.

**Pull request merged**
