### PR TITLE
Convert documentation to asciidoc format

### PR DESCRIPTION
**Pull request by pyokagan**
Preview at https://pyokagan.github.io/se-edu.github.io

After merging, travis needs to be enabled on the repo and the `GITHUB_TOKEN` environment variable set, as usual.

### CODE REVIEW

**Review by damithc — APPROVED** [review]
Had a quick look at the staged site. Looks good. Didn't do a detailed review though. Can go ahead and merge.

**Comment by pyokagan** [comment]
@damithc You'll need to set up Travis and the `GITHUB_TOKEN` environment variable :-)

**Comment by damithc** [comment]
> @damithc You'll need to set up Travis and the GITHUB_TOKEN environment variable :-)

done

**Comment by pyokagan** [comment]
@damithc You'll need to switch the GitHub pages branch to `gh-pages`, after that it should work.

**Comment by damithc** [comment]
uh oh. GitHub forces github.io repos to use master branch.  If nothing else works, we can do what we do in https://markbind.github.io (i.e., redirect to a regular repo site)

**Comment by pyokagan** [comment]
@damithc 
> If nothing else works, we can do what we do in https://markbind.github.io (i.e., redirect to a regular repo site)

It doesn't look so nice if the home page of the website doesn't have a "home page"-like URL, tho. imo.

How about this: we use the `master` branch as the "gh-pages" branch to store the HTML files, and then use another branch (e.g. `docs`) to store the source files?

**Comment by damithc** [comment]
> How about this: we use the master branch as the "gh-pages" branch to store the HTML files, and then use another branch (e.g. docs) to store the source files?

Sure.

**Comment by pyokagan** [comment]
@damithc Done.

**Comment by damithc** [comment]
Nice. :+1:

**Comment by pyokagan** [comment]
setdefaultbranch

@damithc You can also set the default branch to the `docs` branch so that it is displayed by default on the repo. The GitHub pages will still use the `master` branch. (i.e. it's hardcoded :thinking: , I tried it)

**Comment by damithc** [comment]
Done. Also added gave you admin permission to the repo

**Pull request merged**
